#!/bin /bash
# list all the files and directory 
la 

# To change the directory 
cd robot 

# To make the directory
mkdir tech

# to create a file 
touch ronit

# To remove a file 
rm ronit

# To remove a directory 
rmdir tech
