#!/bin/bash
# Navigate to home directory 
cd 

# List contents of directory 
ls -l directory_name 

# Create and navigate tthrough directory 
mkdir -p rounak/kumar
cd rounak/kumar

# Create a file and list its contents 
echo "this is good" > fun.txt
cat fun.txt
