#!/bin/bash
# Create a user 
useradd rounak

# Set password to user 
passwd rounak

# Create a group
groupadd admin

# To add user to group
usermod -aG admin rounak

# Modify user propertise 
usermod -c "Updated Test User" testuser

# To delete the user 
userdel rohan

# To delete the group
groupdel addmin
